### ISSUE TITLE
Deploying existing charts without building

### ISSUE THREAD

**Issue by neocorp** [zbrookle/avionix#34]
Hi @zbrookle , I came accross your post on stackoverflow while looking for a viable solution to deploy helm charts with Python 3. 
What I need might be already baked into Avionix already but couldn't find a documentation regarding how to do this so just wanted to reach out to you.
I'm looking to simply deploy existing helm charts from existing repositories without having to build the specs from ground up. As an example, let's suppose I just want to deploy harbor chart and what I do basically is:
```
helm repo add harbor https://helm.goharbor.io
helm install my-release harbor/harbor
```
Is this possible with Avionix? If not, are there any plans for the implementation?
Thanks

**Comment by zbrookle** [comment]
@neocorp Yes! This is actually something that's very possible with avionix currently. I'm going to add an example to the documentation and I'll link it here when it's done

**Comment by zbrookle** [comment]
@neocorp I just published some new documentation [here](https://avionix.readthedocs.io/en/latest/user_guide/using_external_helm_charts.html). Let me know if you see anything that may need clarification

**Comment by neocorp** [comment]
Thank you so much for the quick feedback and documentation update @zbrookle! I'll have a look and get back to you

**Comment by zbrookle** [comment]
@neocorp Hey just wondering if you got a chance to check this out? I'd like to close it if everything worked out on your end

**Comment by zakatsv** [comment]
Hello @zbrookle I am also looking for a way to deploy existing charts with avionix. I've checked the documentation you've added recently

**Comment by zbrookle** [comment]
@zakatsv You're absolutely right, the documentation could be a bit clearer. Do you think it would help if I showed the file structure output and the Chart.yaml output in the documentation?

**Comment by zakatsv** [comment]
@zbrookle Thank you for getting back to me. I believe there should be no Chart.yaml when deploying a chart from a public repository since the goal is to install an existing chart but not to build a new with with a third-party chart given as a dependency. So, in case it is possible to install a chart without building a new one, it would be really helpful if you could add an example for such a use case.

**Comment by zbrookle** [comment]
@zakatsv If you just want to install one chart on its own, this may not be the right package for you. The intent of this package is more so to build and deploy new charts, rather than just install existing ones. A new chart can include dependencies on other charts which is why this feature is included, but I would recommend using helm directly for a simple use case. Hopefully that clarifies things

**Comment by zakatsv** [comment]
Yes, thank you very much @zbrookle. That definitely clarifies the things.
